name: Deploy company page to github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy: 
    runs-on: ubuntu-latest

    steps:
      #checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3
      
      # setup nodejs
      - name: SetupJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Install dependencies
      - name: Install dependencies
        run: npm install
      
      # Build the project
      - name: Build the project
        run: npm run build

      # Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
        
        